/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StarfinderIndexRouteImport } from './routes/starfinder/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StarfinderIndexRoute = StarfinderIndexRouteImport.update({
  id: '/starfinder/',
  path: '/starfinder/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/data/': typeof DataIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/starfinder/': typeof StarfinderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/data': typeof DataIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/starfinder': typeof StarfinderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/data/': typeof DataIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/starfinder/': typeof StarfinderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar/' | '/data/' | '/settings/' | '/starfinder/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/data' | '/settings' | '/starfinder'
  id: '__root__' | '/' | '/calendar/' | '/data/' | '/settings/' | '/starfinder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  DataIndexRoute: typeof DataIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StarfinderIndexRoute: typeof StarfinderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starfinder/': {
      id: '/starfinder/'
      path: '/starfinder'
      fullPath: '/starfinder/'
      preLoaderRoute: typeof StarfinderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  DataIndexRoute: DataIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StarfinderIndexRoute: StarfinderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
